version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - pocketbase
    volumes:
      - .:/app
      - /app/node_modules
      - ./public/uploads:/app/public/uploads  
    restart: unless-stopped

