version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - pocketbase
    volumes:
      - .:/app
      - /app/node_modules
      - ./public/uploads:/app/public/uploads  # Local storage for uploads
    restart: unless-stopped

  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile.pocketbase
    ports:
      - '8080:8080'
    volumes:
      - pocketbase_data:/pb_data  # Persist PocketBase data
    env_file:
      - .env
    restart: unless-stopped

volumes:
  pocketbase_data:
